# Generated by Django 6.0 on 2025-12-24 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='meal_types',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meal_types', to='restraurant_app.mealtype'),
            preserve_default=False,
        ),
    ]
