# Generated by Django 6.0 on 2025-12-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_app', '0002_mealcategory_meal_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealcategory',
            name='image',
            field=models.ImageField(default=1, upload_to='categories/'),
            preserve_default=False,
        ),
    ]
