# Generated by Django 6.0 on 2025-12-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_app', '0003_mealcategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mealcategory',
            name='meal_types',
        ),
    ]
