# Generated by Django 6.0 on 2025-12-27 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_app', '0004_remove_mealcategory_meal_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.AddField(
            model_name='mealtype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='meal_types/'),
        ),
        migrations.DeleteModel(
            name='MealCategory',
        ),
    ]
