# Generated by Django 6.0 on 2025-12-27 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_app', '0005_remove_meal_category_mealtype_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('working_age', models.IntegerField()),
                ('is_free', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='selfies/')),
                ('phone_number', models.IntegerField()),
            ],
        ),
    ]
