# Generated by Django 6.0 on 2025-12-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restraurant_app', '0006_deliveries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveries',
            name='phone_number',
            field=models.CharField(),
        ),
    ]
